
services:  
  db: 
    image: postgres:latest
    environment:
      POSTGRES_DB: sis_db
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_pass        
    
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sis_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_CONN: "host=db port=5432 dbname=sis_db user=sis_user password=sis_pass"
    networks:
      - sis_net
    stdin_open: true
    tty: true

volumes:
  db_data:

networks:
  sis_net:
    driver: bridge
